# Generated by Django 3.2.16 on 2022-11-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('payment_method', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.DateField(null=True)),
            ],
            options={
                'db_table': 'payment_method',
                'managed': False,
            },
        ),
    ]
